Repository 3xplcom/Core, pull requests merged in 2024-09, with the labels that each got.

#90 Add Solana token modules
  .env.example
  .gitignore
  CONTRIBUTORS.md
  Engine/Crypto/Base58.php
  Engine/Crypto/Sodium.php
  Modules/Common/SVMMainModule.php
  Modules/Common/SVMTokenModule.php
  Modules/Common/SVMTraits.php
  Modules/Genesis/SolanaTokenList.data
  Modules/SolanaFTModule.php
  Modules/SolanaMainModule.php
  Modules/SolanaNFTModule.php
Labels: Refactor blockchain, Add module

#91 Add L1 fee processing to OP Stack (Optimism, Base, opBNB, et al.)
  Engine/Enums.php
  Modules/BaseMainModule.php
  Modules/Common/EVMMainModule.php
  Modules/Common/EVMTraits.php
  Modules/OptimismMainModule.php
  Modules/opBNBMainModule.php
Labels: Refactor blockchain

#102 Add Blast support
  .env.example
  Modules/BlastERC1155Module.php
  Modules/BlastERC20Module.php
  Modules/BlastERC721Module.php
  Modules/BlastMainModule.php
  Modules/BlastTraceModule.php
  Modules/Common/EVMMainModule.php
Labels: Add blockchain

#95 Add text data to `api_get_transaction_specials()` in UTXO modules
  Modules/Common/UTXOMainModule.php
Labels: API, Beta test
